# Site settings
title: Prasetyo Andi blog
email: 
description: "Bualan enjiner yang merangkap menjadi tukang komputer"
baseurl: ""
url: "http://prasetyoandi.github.io/"
twitter_username: scalartensor
github_username:  prasetyoandi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
